apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: buildversionsapi-secret
  namespace: buildversionsapi
spec:
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: buildversionsapi-secret
      namespace: buildversionsapi

