apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis
resources:
- namespace.yaml
- service.yaml
- deployment.yaml
#Remember to publish port 6379 in k3d-k3s.serverlb:
#k3d node edit k3d-k3s-serverlb --port-add 6379:6379