#Needs a port mapping when creating the cluster to be accessible from outside 3307:3307
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: LoadBalancer
  ports:
  - name: mysql
    port: 3307
    targetPort: 3307
  selector:
    app: mysql
